// <auto-generated />
using AutobotBlazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutobotBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230502212247_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutobotBlazor.Shared.Models.CandidateResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CentreId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ExamDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreviousHostIps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("SessionRef")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("TotalAttempted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CandidateResponses");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.ExamTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("HostIPId")
                        .HasColumnType("bigint");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HostIPId")
                        .IsUnique();

                    b.ToTable("ExamTimes");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.ExamType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("HostIPId")
                        .HasColumnType("bigint");

                    b.Property<string>("oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HostIPId")
                        .IsUnique();

                    b.ToTable("ExamTypes");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.HostIP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateResponseId")
                        .HasColumnType("bigint");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateResponseId");

                    b.ToTable("HostIPs");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.ExamTime", b =>
                {
                    b.HasOne("AutobotBlazor.Shared.Models.HostIP", "HostIP")
                        .WithOne("time")
                        .HasForeignKey("AutobotBlazor.Shared.Models.ExamTime", "HostIPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostIP");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.ExamType", b =>
                {
                    b.HasOne("AutobotBlazor.Shared.Models.HostIP", "HostIP")
                        .WithOne("_id")
                        .HasForeignKey("AutobotBlazor.Shared.Models.ExamType", "HostIPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostIP");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.HostIP", b =>
                {
                    b.HasOne("AutobotBlazor.Shared.Models.CandidateResponse", "CandidateResponse")
                        .WithMany("HostIPs")
                        .HasForeignKey("CandidateResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateResponse");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.CandidateResponse", b =>
                {
                    b.Navigation("HostIPs");
                });

            modelBuilder.Entity("AutobotBlazor.Shared.Models.HostIP", b =>
                {
                    b.Navigation("_id")
                        .IsRequired();

                    b.Navigation("time")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
